### ISSUE TITLE
Corrupting JPEG

### ISSUE THREAD

**Issue by sin6pi7** [snorpey/glitch-canvas#20]
Hi snorpey,
I am trying to understand why corrupting single bytes in the JPEG file affects a much bigger part of the picture. Let take as an example https://snorpey.github.io/jpg-glitch/ with arguments: 
- amount: 1,
- seed: 57,
- iterations: 1

This is the resulting image:
![image](https://cloud.githubusercontent.com/assets/5755502/24105184/087cd7d6-0d7c-11e7-8daa-d2619e4a3d3c.png)

Passing these arguments to glitchByteArray function would result in one iteration, hence single byte corruption. The resulting image though has a much bigger part changed in a way, that you can still see the original part, but in a different color range.
In the "Info" section on that page one can read "Because of the way JPEG encoding works, the corrupted file still shows a corrupted image.", which links to Wikipedia, but I still have a hard time understanding why that happens.
From what I understand encoding into JPEG format means:
1. Downsampling single bytes,
2. Dividing image into 8x8 pixel blocks,
3. Transforming 8x8 pixel matrices into 8x8 real numbers matrices,
4. Using Huffman encoding on each of the resulting matrices, but iterating in a zig-zag way instead of left-right and top-down.

Could you please explain why corrupting a single byte affects a bigger part of the picture? And if my encoding description is not correct, could you please correct me?

Thanks!

**Comment by snorpey** [comment]
hey @sin6pi7 thank you for your interest in this library.

to be perfectly honest, i don't know _exactly_ why the manipulation works, but i'll try to give you an explanation of what i think happens (which may be very wrong, i'm not a computer scientist):

the image goes through the following steps when glitching:

* [convert image to `ImageData`](https://github.com/snorpey/glitch-canvas/blob/master/src/input/browser/fromImage.js)
* [convert `ImageData` to `base64 Data URI`](https://github.com/snorpey/glitch-canvas/blob/master/src/glitch/browser/imageDataToBase64.js)
* [convert `base64` to `ByteArray`](https://github.com/snorpey/glitch-canvas/blob/master/src/glitch/base64ToByteArray.js)
* [alter Bytes in `ByteArray`](https://github.com/snorpey/glitch-canvas/blob/master/src/glitch/glitchByteArray.js) this is where the data is corrupted
* [convert `ByteArray` to `Base64`](https://github.com/snorpey/glitch-canvas/blob/master/src/glitch/byteArrayToBase64.js)
* decode + display image with base64 Data uri.

this means that the glitch happens when the browser tries to decode and display the manipulated base64 uri. this is also the reason why different browsers can yield different results.

as to why the glitch affects a larger area than 8x8 px, i don't really know, unfortunately.

sorry i can't give you a better explanation…

**Comment by snorpey** [comment]
closing this issue for now. please let me know in case you want me to clarify something…
